### ISSUE TITLE
Possibility of "splitting a config" with 0.9.x?

### ISSUE THREAD

**Issue by ildar170975** [twrecked/hass-virtual#113]
In 0.8.x there is a possibility to split a config - keep settings in different packages.
For instance, I may keep some `device_tracker` entities in `/config/folder_1/file_1.yaml`, other `device_tracker` entities - in `/config/folder_2/file_2.yaml`.
Just installed 0.9.x - and seems that all settings now have to be kept in ONE file.
Do not find it convenient.
Am I doing smth wrong?

Probably I may create one more `virtual_test.yaml` and move there some entries (consider these entries as "test only entries") from `virtual.yaml` and then ADD one more integration:
![image](https://github.com/user-attachments/assets/d0e6809c-a69e-4f3d-84ec-eca9d283d63e)
but that means that I have TWO files which do not belong to any package.

**Comment by twrecked** [comment]
I'll see if I can support both mechanisms.

I thought I had to do one or the other but that doesn't seem to be the case.

**Comment by twrecked** [comment]
Can you try _b14_ release. I added this config option to allow the old behaviour to work.

```yaml
virtual:
  yaml_config: True
```

You may have to delete the imported integration before restarting.  Sorry for the awkwardness around this, I assumed you could only have 1 config mechanism or the other. It turns out that is not true.

**Comment by ildar170975** [comment]
@twrecked 
Sorry, I do not understand...

Assume before 0.9 there was this code in some "virtual_trackers.yaml":
```
device_tracker:
  - platform: virtual
    devices:
      - name: virtual_tracker_1
        peristent: True
        location: home
```
which created `device_tracker.virtual_tracker_1`.

In 0.9 to add this tracker I need to add a new entry in UI & import some "virtual.yaml" file (can have a diff. name):
```
version: 1
devices:
  virtual_tracker_1:
  - platform: device_tracker
    name: virtual_tracker_1
```

Do yo mean that in 0.9 it is possible:
-- either use the new way ("add entry" in UI -> import some "virtual.yaml")
-- or keep using the old way - declaring sensors in yaml?

**Comment by twrecked** [comment]
In 0.9 you can mix both ways of defining devices.  To clarify, I have the following config and it's working:

_configuration.yaml_; I just put it straight in this file.
```yaml
virtual:
  yaml_config: True

# later on I include with this...
device_tracker: !include device_trackers.yaml
```

_device_trackers.yaml_; which I load from `configuration.yaml`.
```
- platform: virtual
  devices:
    - name: virtual_old_test
    - name: virtual_old_test2
```

_virtual-test.yaml_; which I add in through the intergrations.
```
version: 1
devices:
  virtual_tracker_1:
  - platform: device_tracker
    name: virtual_tracker_1
```

I'm guessing it's  not parsing the `yaml_config` piece. Can you show me how you include it, I might need to beef that up.
