### ISSUE TITLE
Calling "device_tracker.see" service causes an error in Log

### ISSUE THREAD

**Issue by ildar170975** [twrecked/hass-virtual#115]
0.9.0b11

virtual.yaml:
```
version: 1
devices:

  virtual_tracker_1:
  - platform: device_tracker
    name: virtual_tracker_1

  virtual_tracker_2:
  - platform: device_tracker
    name: virtual_tracker_2

  virtual_tracker_3:
  - platform: device_tracker
    name: virtual_tracker_3
```
Integration is added:
![image](https://github.com/user-attachments/assets/0355baa3-ec72-4a47-b551-f03a7fd39725)

Three entities are created:
![image](https://github.com/user-attachments/assets/775ca2c9-ba47-4e75-9f12-3cd1f1f7f156)

![image](https://github.com/user-attachments/assets/16e35188-e55e-432e-aa93-448ab1247c63)

Trying to call a service:
```
      service: device_tracker.see
      data:
        dev_id: virtual_tracker_1
        gps:
          - 65.73062649311031
          - 5.273437500000001
        gps_accuracy: 10
```
With 0.8.x this call worked fine.
Now I see this error in Log:
2024-07-12 21:34:53.432 ERROR (MainThread) [homeassistant.components.device_tracker] The see service is not supported for this entity device_tracker.virtual_tracker_1

The entity is not updated after the service call.

**Comment by ildar170975** [comment]
Probably I should use a `virtual.move` service mentioned in Docs. In this case please add a description of how this service can be used. 
From what I see - only a zone can be defined, not coords & accuracy:
![image](https://github.com/user-attachments/assets/b33fc786-429b-4b12-a1d6-fe6451a8967f)

**Comment by twrecked** [comment]
Should be fixed in 0.9.0b12

And yes, you have to use move. `device.see` only works with legacy devices.

**Comment by ildar170975** [comment]
@twrecked 
Thanks a LOT for adding coords for `virtual.move` service.
This call works:
```
    - service: virtual.move
      target:
        entity_id: device_tracker.virtual_tracker_1
      data:
        gps:
          latitude: 65.73062649311031
          longitude: 5.273437500000001
```
