### ISSUE TITLE
Processing wrong user config may give unexpected results

### ISSUE THREAD

**Issue by ildar170975** [twrecked/hass-virtual#116]
0.9.0b11

Assume there is a `virtual.yaml` file in `/config`:
```
version: 1
devices:

  Light hall_ceiling:
  - initial_value: 'on'
    support_brightness: true
    initial_brightness: 100
    support_color: true
    initial_color:
    - 0
    - 255
    support_color_temp: true
    initial_color_temp: 255
    support_white_value: true
    initial_white_value: 240
    platform: light
    name: hall_ceiling
```
Let's add a new integration:
![image](https://github.com/user-attachments/assets/90094543-aa5d-427c-8632-bf5b35951d3f)

Note that here I made a mistake - inputted a wrong filename `virtual.yml` (extension is wrong).
An new entry is added - w/o entities created:
![image](https://github.com/user-attachments/assets/c51015d9-e0be-4047-a7fd-6bc3856d8163)

And there are no errors in Log.
Let's delete this wrong entry:
![image](https://github.com/user-attachments/assets/481bc725-f4ce-4e79-9cb9-89475a60240b)

Then I see an error in Log:
2024-07-12 22:19:27.102 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry imported - virtual for virtual
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 801, in async_unload
result = await component.async_unload_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/virtual/__init__.py", line 168, in async_unload_entry
await bcfg.async_delete()
File "/config/custom_components/virtual/cfg.py", line 379, in async_delete
await _delete_meta_data(self._hass, self._group_name)
File "/config/custom_components/virtual/cfg.py", line 152, in _delete_meta_data
devices.pop(group_name)
KeyError: 'imported'

Then add a correct entry:
![image](https://github.com/user-attachments/assets/f7d79735-1622-4548-8a64-37e7a99ad1de)

But there is an error:
![image](https://github.com/user-attachments/assets/0f25fe21-041c-451e-9cef-c78647d0d311)

After changing it to "imported_1" an entry is created:
![image](https://github.com/user-attachments/assets/b21e97b8-787a-46ef-b92a-4b551028850e)

Suggestion:
1. Do not create an entry in case of a wrong input (here - a wrong file).
2. Allow a user to use same "group" value since there is no other existing entries.
