### ISSUE TITLE
Can't find entity

### ISSUE THREAD

**Issue by camels84** [twrecked/hass-virtual#12]
Hi,
i install this integration directly from hacs, and i can't see the virtual entity... 
Can you provide a better install guide? I already had the virtual device in configuration.yaml
Hass-Virtual version: v0.7.1
core: core-2021.4.3
supervisor: supervisor-2021.03.9

I really apreciate helping to solve this.

**Comment by twrecked** [comment]
Can you paste your configuration in here? Also, as an example, the following:

```yaml
- platform: virtual
  name: "TV Outlet"
  initial_value: 'on'
```

will create a component called `switch.virtual_tv_outlet`. The `virtual` is added by Home Assistant.

**Comment by camels84** [comment]
I already do it,

`             
virtual:
      switch:
      - platform: virtual
        entity: virtual
        name: 'Switch_1'
      - platform: virtual
        name: 'Switch_2' `

But i can't find the component. Convfiguration doesn't give any error, so it recognizes the "virtual", but i can't find in home assistant anything with the name virtual.

**Comment by camels84** [comment]
Already found it, i don't know why, but i think your instruction wasn't too clear,
![imagem](https://user-images.githubusercontent.com/78514331/114641219-95c4e300-9cc9-11eb-9d18-05a7f264e3e7.png)

i put like this:

> switch:
  - platform: virtual
    name: "TV Outlet 2"
#    initial_value: 'on'         
virtual:
    - platform: virtual
      name: "TV Outlet"
      initial_value: 'on'
      switch:
      - platform: virtual
        entity: virtual
        name: 'Switch_1'
        initial_value: 'on'
      - platform: virtual
        name: 'Switch_2' 
        initial_value: 'on'

and the only that worked was "TV Outlet 2", that is defined outside the "Virtual:"

**Comment by twrecked** [comment]
Sorry, my instructions assume you are familiar with Home Assistant config. Try this in `configuration.yaml`:

```yaml
virtual:

switch:
  platform: virtual
    name: "TV Outlet 2"
    initial_value: 'on'
  platform: virtual
    name: "TV Outlet"
    initial_value: 'on'
  platform: virtual
    name: 'Switch_1'
    initial_value: 'on'
  platform: virtual
    name: 'Switch_2'
    initial_value: 'on'
```

`virtual:` and `switch:` sections should only appear once in your entire configuration.
