### ISSUE TITLE
[FR] Add "gps_accuracy" for "virtual.move"

### ISSUE THREAD

**Issue by ildar170975** [twrecked/hass-virtual#127]
Currently we can use this service call:
```
    - service: virtual.move
      target:
        entity_id: device_tracker.virtual_tracker_1
      data:
        gps:
          latitude: 65.73062649311031
          longitude: 5.273437500000001
```
Unfortunately, we cannot add a "gps_accuracy" property.

Why it could be desirable?
Virtual tracker may be used:
-- for testing
-- for emulating "normal" `device_tracker` entities: we can feed coords & accuracy (gathered from some other source) for a virtual tracker.

Please add an optional `gps_accuracy` attribute for the `virtual.move` service call.
