### ISSUE TITLE
"person" entity not following a virtual "device_tracker"

### ISSUE THREAD

**Issue by ildar170975** [twrecked/hass-virtual#129]
Create this `device_tracker`:
```
version: 1
devices:

  virtual_tracker_1:
  - platform: device_tracker
    name: virtual_tracker_1
```
Then move the tracker to somewhere (not matching any registered zones):
```
        service: virtual.move
        target:
          entity_id: device_tracker.virtual_tracker_1
        data:
          gps:
            latitude: 65.73
            longitude: 5.27
```
Make sure that the `device_tracker` has moved:
![изображение](https://github.com/user-attachments/assets/d4a41072-4caf-4908-96eb-ff65c485efc7)

Then create a `person` & associate it with that `device_tracker`:
![изображение](https://github.com/user-attachments/assets/f123f158-2a36-418b-8668-cd69eb64b2e8)

Check a state of this `person`:
![изображение](https://github.com/user-attachments/assets/2cf399f0-851f-482e-b159-f78fa329198d)
Note that the `person` is in the right position.

Then move the tracker to somewhere (not matching any registered zones):
```
        service: virtual.move
        target:
          entity_id: device_tracker.virtual_tracker_1
        data:
          gps:
            latitude: 50.73
            longitude: 15.27
```
Make sure that both the `device_tracker` & the `person` have moved:
![изображение](https://github.com/user-attachments/assets/b6c5905b-b2ee-4182-85ab-802c26adbe50)

Then move the tracker to some particular zone:
```
        service: virtual.move
        target:
          entity_id: device_tracker.virtual_tracker_1
        data:
          gps:
            latitude: 56.322415124967215
            longitude: 43.94578456878662
```
where coordinates are used for this zone:
```
zone:
  - name: n_novgorod_vokzal
    latitude: 56.322415124967215
    longitude: 43.94578456878662
    radius: 200
    passive: false
    icon: mdi:train
```
And see that the `device_tracker` has moved, but the `person` became `unknown`:
![изображение](https://github.com/user-attachments/assets/b0e40fb8-357c-456d-a36a-0919fda48e0c)

Then go to Dev tools -> Set state and manually edit a `source_type` attribute from `virtual` to `gps`:
![изображение](https://github.com/user-attachments/assets/5edce597-cb52-401d-8b9b-0b7f6386a28f)

Then see that the `person` entity properly updated:
![изображение](https://github.com/user-attachments/assets/4b0d96e1-7626-4732-99f7-9fb1a385ebba)

I guess that `source_type = virtual` prevents a proper processing of a `person` entity.
Suggest to set `source_type = gps` in every call of `virtual.move` if coords are defined in a service call.
