### ISSUE TITLE
Virtual light entity does not allow changing color

### ISSUE THREAD

**Issue by bealex** [twrecked/hass-virtual#131]
(installed version: 0.9b15)

Here is the light I created in virtual.yaml:
```yaml
  Another Light:
  - platform: light
    name: Another Light
    initial_value: 'on'
    support_brightness: true
    initial_brightness: 100
    support_color: true
    initial_color: [42,100]
    support_color_temp: true
    initial_color_temp: 255
    initial_availability: true
```
When I try to change color (not color_temp) in the UI, Home Assistant does not allow it. If I change it from API with something like this:
```json
{"id":27,"service":"turn_on","domain":"light","type":"call_service","target":{"entity_id":"light.another_light_2"},"service_data":{"transition":0,"hs_color":[240,100]}}
```
I get 
```json
{"id":27,"type":"result","success":true,"result":{"context":{"id":"01J6FAJZW6VS7V3YCNBA86H3AJ","parent_id":null,"user_id":"..."}}}
```
But then I receive a state update with color mode `color_temp`, that renders my request useless. But color_mode should be changed to some kind of color mode (xy, hs, rgb etc.)
