### ISSUE TITLE
virtual.yaml file overwritten

### ISSUE THREAD

**Issue by jack68k** [twrecked/hass-virtual#144]
I just installed Virtual Devices for the first time and discovered the following sequence of actions will cause `virtual.yaml` to be overwritten with an apparent attempt to convert non-existent configuration from pre-0.9 versions:

1. Initial state: Virtual Devices is not installed
2. Create `/config/virtual.yaml` and define a virtual device, for example:
  ```yaml
  version: 1
  devices:
   Virtual Motion Sensor:
    - platform: binary_sensor
      name: Virtual Motion
      initial_value: 'off'
      class: motion
  ```
3. Install __Virtual Devices 0.9.0b18__ from HACS
4. Add `virtual:` to `/config/configuration.yaml`
    ```yaml
    virtual:
    ```
5. Restart Home Assistant
6. Result: `/config/virtual.yaml` is overwritten with the following:
   ```yaml
   version: 1
   devices: {}
   ```

It's not clear to me if I've done something incorrectly that will result in `virtual.yaml` being overwritten again in the future. I was able to re-create the file and reload the Virtual Devices integration and the file has remained unchanged so far.
