### ISSUE TITLE
HA shows the warning about light color temperature for my installation of Virtual

### ISSUE THREAD

**Issue by bealex** [twrecked/hass-virtual#152]
Warning from the logs:
```
2025-01-15 18:04:56.918 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'virtual' is using mireds for coldest light color temperature, when it should be adjusted to use the kelvin attribute `_attr_max_color_temp_kelvin` or override the kelvin property `max_color_temp_kelvin`, possibly with default DEFAULT_MAX_KELVIN (see https://github.com/home-assistant/core/pull/79591). This will stop working in Home Assistant 2026.1, please create a bug report at https://github.com/twrecked/hass-virtual/issues
```

Virtual Configuration:
```yaml
version: 1
devices:
  Garage Door:
  - platform: cover
    name: Garage Door
    initial_value: 'closed'
    class: garage_door
    initial_availability: true
    open_close_duration: 10
    open_close_tick: 1
  Door Lock:
  - platform: lock
    name: Door Lock
    initial_availability: true
    initial_value: locked
    locking_time: 3
    jamming_test: 5

  Test Fan:
  - platform: fan
    speed: true
    speed_count: 5
    direction: true
    oscillate: true

  Binary Sensor Generic:
  - platform: binary_sensor
    name: Binary Sensor Generic
    initial_value: 'off'
    class: presense
    initial_availability: true
  Smoke 1:
  - platform: binary_sensor
    name: Smoke 1
    initial_value: 'off'
    class: smoke
    initial_availability: true
  Smoke 2:
  - platform: binary_sensor
    name: Smoke 2
    initial_value: 'off'
    class: smoke
    initial_availability: true
  Smoke 3:
  - platform: binary_sensor
    name: Smoke 3
    initial_value: 'off'
    class: smoke
    initial_availability: true
  Smoke 4:
  - platform: binary_sensor
    name: Smoke 4
    initial_value: 'off'
    class: smoke
    initial_availability: true
  Сarbon Monoxide 1:
  - platform: binary_sensor
    name: Сarbon Monoxide 1
    initial_value: 'off'
    class: carbonMonoxide
    initial_availability: true
  Сarbon Monoxide 2:
  - platform: binary_sensor
    name: Сarbon Monoxide 2
    initial_value: 'off'
    class: carbonMonoxide
    initial_availability: true
  Сarbon Monoxide 3:
  - platform: binary_sensor
    name: Сarbon Monoxide 3
    initial_value: 'off'
    class: carbonMonoxide
    initial_availability: true
  Moisture 1:
  - platform: binary_sensor
    name: Moisture 1
    initial_value: 'off'
    class: moisture
    initial_availability: true
  Moisture 3:
  - platform: binary_sensor
    name: Moisture 3
    initial_value: 'off'
    class: moisture
    initial_availability: true

  Temperature:
  - platform: sensor
    name: Temperature
    class: temperature
    initial_value: '21.4'
    initial_availability: true
    unit_of_measurement: °C
    unique_id: NOTYET
    device_id: NOTYET
    entity_id: NOTYET

  CO2:
  - platform: sensor
    name: CO2
    class: co2
    initial_value: '4321'
    initial_availability: true
    unit_of_measurement: ppm
    unique_id: NOTYET
    device_id: NOTYET
    entity_id: NOTYET

  AC Temperature:
  - platform: sensor
    name: AC Temperature
    class: temperature
    initial_value: '21.4'
    initial_availability: true
    unit_of_measurement: C
    unique_id: NOTYET
    device_id: NOTYET
    entity_id: NOTYET

  Light One:
  - platform: light
    name: Light One
    initial_value: 'on'
    support_brightness: true
    initial_brightness: 100
    support_color: true
    initial_color:
    - 0
    - 255
    support_color_temp: true
    initial_color_temp: 255
    support_white_value: true
    initial_white_value: 240
    initial_availability: true
  Light Two:
  - platform: light
    name: Light Two
    initial_value: 'off'
    support_brightness: true
    initial_brightness: 100
    support_color: true
    initial_color:
    - 0
    - 255
    support_color_temp: true
    initial_color_temp: 255
    support_white_value: true
    initial_white_value: 240
    initial_availability: true
  Light Simple:
  - platform: light
    name: Light Simple
    initial_value: 'off'
    support_brightness: true
    initial_brightness: 100
    support_color: false
    support_color_temp: false
    support_white_value: false
    initial_availability: true
  Another Light:
  - platform: light
    name: Another Light
    initial_value: 'on'
    support_brightness: true
    initial_brightness: 100
    support_color: true
    initial_color: [42,100]
    support_color_temp: true
    initial_color_temp: 255
    initial_availability: true

  Test Switch One:
  - platform: switch
    name: Test Switch One
  Test Switch Two:
  - platform: switch
    name: Test Switch Two
  AC Heater:
  - platform: switch
    name: AC Heater
```
