### ISSUE TITLE
second entity for sensor?

### ISSUE THREAD

**Issue by michapr** [twrecked/hass-virtual#32]
Hi,
is it possible to add a second  (or third) entity to sensor for creating temp/hum/batt sensor?

Thanks!

**Comment by Tony763** [comment]
Hi, I create separate sensor for each type an then place them into same Area:
```
sensor:
  # ESP8266_AirSensor_1
  - platform: virtual
    name: '!babi co2'
    class: carbon_dioxide
    initial_value: 0
    initial_availability: false
  - platform: virtual
    name: '!babi temp'
    class: temperature
    initial_value: 0
    initial_availability: false
  - platform: virtual
    name: '!babi humi'
    class: humidity
    initial_value: 0
    initial_availability: false
```

![image](https://user-images.githubusercontent.com/5598750/178120256-b0f315dc-1729-4987-8161-62e23e6b5a1d.png)
