### ISSUE TITLE
Virtual Binary Sensor resets itself after certain time

### ISSUE THREAD

**Issue by Draganis** [twrecked/hass-virtual#36]
I have Tuya WiFi Window Sensors in use. Though they are shown as "not available" when they idle around I made automations for every window sensor to update a virtual binary_sensor on state change. Works like a charm in Winter. In Summer the windows are mostly open  (sometimes for days) and now the virtual binary sensors reset theirselves to the initial value from time to time.

HA Version: Home Assistant 2022.8.6
Virtual Components Version: 0.7.7

**Virtual sensor**:

```
- platform: virtual
  name: "Schlafzimmer Fenster"
  initial_value: 'off'
  class: window
  initial_availability: true
```

**Automations**:

```
- id: '1660157912871'
  alias: Schlafzimmer Fenster auf
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.schlafzimmer_fenster_tuya
    to: 'on'
  condition: []
  action:
  - service: python_script.set_states
    data:
      entity_id: binary_sensor.virtual_schlafzimmer_fenster
      state: 'on'
      icon: mdi:window-open
  mode: single
- id: '1660157966855'
  alias: Schlafzimmer Fenster zu
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.schlafzimmer_fenster_tuya
    to: 'off'
  condition: []
  action:
  - service: python_script.set_states
    data: {}
  mode: single
```

**python_scripts/set_state.py** : 

```
inputEntity = data.get('entity_id')
inputStateObject = hass.states.get(inputEntity)
inputState = inputStateObject.state
inputAttributesObject = inputStateObject.attributes.copy()

newState = data.get('state')
if newState is not None:
    inputState = newState
    
newIcon = data.get('icon')
if newIcon is not None:
    inputAttributesObject['icon'] = newIcon

hass.states.set(inputEntity, inputState, inputAttributesObject)
```
