### ISSUE TITLE
support_brightness does'nt work

### ISSUE THREAD

**Issue by jlfrucot** [twrecked/hass-virtual#41]
trying to use virtual light, i experiment that issue : 
[support_brightness] is an invalid option for [light.virtual]

 Home Assistant 2022.11.1 
Supervisor 2022.10.2 
Operating System 9.3 
Interface utilisateur : 20221102.1 - latest 

RPI 3+

**Comment by Tony763** [comment]
Hello @jlfrucot could You check which version of hass-virtual You use and provide steps to reproduce the above error?

I just upgraded HA to 2022.11.3 and with version 7.7, everything works as expected.

My sample config:
```yml
 # ESP32_Aquarium
  - platform: virtual
    name: '!aqua UV'
    initial_value: 'off'
    initial_brightness: 0
    support_brightness: true
    support_color: false
    initial_color: [0,255]
    support_color_temp: false
    initial_color_temp: 0
    support_white_value: false
    initial_white_value: 0
    initial_availability: false

```
