### ISSUE TITLE
Virtual light devices and not just entities

### ISSUE THREAD

**Issue by etokheim** [twrecked/hass-virtual#53]
Hi! I might have overlooked something, but I can't seem to figure out how to add a light as a device. Is that possible with the hass-virtual component?

I want to make a scene with the virtual lights, but scenes only support devices...

**Comment by twrecked** [comment]
This doesn't work? They appear as entities although I've never tried one in a scene. I don't have my test system running at the moment but I'll check later.

```yaml
light:
  - platform: virtual
    name: 'Light 1'
```

**Comment by etokheim** [comment]
Thanks!

My understanding is that a device is kind of a group of entities and that the scene creation tool only takes in devices.

I found that I could reference entities when manually editing the scenes.yaml file. Applying the scene changed the lights, but it's very tiresome editing scenes in yaml, compared to the UI.

I used the light from the readme (worked fine, and without any errors):
```yaml
light:
  - platform: virtual
    name: 'Light 1'
    initial_value: 'on'
    support_brightness: true
    initial_brightness: 100
    support_color: true
    initial_color: [0,255]
    support_color_temp: true
    initial_color_temp: 255
    support_white_value: true
    initial_white_value: 240
    initial_availability: true
```
