### ISSUE TITLE
Virtual device is not created

### ISSUE THREAD

**Issue by gitcodeB** [twrecked/hass-virtual#61]
![image](https://user-images.githubusercontent.com/90979173/229346577-18011148-de21-448f-be79-b361ac924d01.png)

I did like above and restart HA.

![image](https://user-images.githubusercontent.com/90979173/229346767-d70bf0e0-eb29-446b-bc9a-b17c84c70aac.png)
![image](https://user-images.githubusercontent.com/90979173/229346782-cfc191d4-e1d2-4777-a3db-c9bd5c98f930.png)

But the device doesn't appear.
What is the problem?

**Comment by Tony763** [comment]
Hi @codinghb, try it like this:

```
virtual:

fan:
  - platform: virtual
    name: "remote fan"
    speed: True
    speed_count: 4
    direction: False
    oscillate: True
    initial_availability: True
```

**Comment by codinghb** [comment]
> 

thanks for reply.
I did, but it doesn't be still created.

**Comment by Tony763** [comment]
Even after HA restart? Coul You post a log here?

**Comment by codinghb** [comment]
> Even after HA restart? Coul You post a log here?

Yes I restarted HA several times.
Where is the log you want and which keyword?

**Comment by codinghb** [comment]
I 

> Even after HA restart? Coul You post a log here?

I found the reason.
I already wrote other template fan and have it.

The code's order is.. 

Line 40 
fan:
  - platform: template..
  - 
Line 50 
fan:
  - platform: virtual...

After deleting code for template fan, the virtual device was created. 

so, Can't I have your virtual device and template fan at the same time?


In addition, I found virtual fan is not created two more.

For exmaple, 

Line 1 
fan:
  - platform: virtual
    name: fan 1
..

Line 10
fan:
  - platform: virtual
    name: fan 2

Only fan 1 was created and fan 2 wasn't created.

Can't I have two more virtual devices?


Thanks.

**Comment by twrecked** [comment]
You can. But you can't have more than 2 `fan:` entries, that is a Home Assistant configuration limitation/design.

```yaml
fan:
- platform: virtual
  name: fan 1
- platform: virtual
  name: fan 2
```
