### ISSUE TITLE
Virtual Entities Can't Be Found, Please Help!!

### ISSUE THREAD

**Issue by ifeanyi-igweze** [twrecked/hass-virtual#62]
I can't seem to find the virtual entities, heck I don't even know if they were created.

I tried looking at the log, but cant find an error about it.

added the debug code to my config but just added a whole lot to the log file and I basically got lost in that.

I read the documentation you suggested to the other guy but got confused later on.

You kept on mentioning sharing the log, how do I do that?

Please help, been stuck on this for weeks. I've literally deleted and redownloaded the integration ☹️

**Comment by ifeanyi-igweze** [comment]
Just read through the closed issues and realized my problem. Oh wow!

This was my initial code

```
virtual:
  switch:
    - platform: virtual
      name: fakeswitch
```

Then after reading I changed it to this

```
virtual:

switch:
  - platform: virtual
    name: fakeswitch
```
And it worked!!
I found the entity after restarting.
