### ISSUE TITLE
Virtual Components v0.8.0.1 not working with core_2023.11.2

### ISSUE THREAD

**Issue by CharlyNaseweis** [twrecked/hass-virtual#74]
Hi there,
 I have to virtual switches in my configuration.yaml which are worked perfectly befor uprading to HA core_2023.11.2. If I do a downgrade, they are working as usual. 
I also can set the switches in the developer tools or manually on the dashboard. The problem is, that they are not chooseable in the automations. 
I already tried a lot like a complete reastart of HA, setting manually the switches but I cannot get it working in the automation. 

My configuration.yaml looks like this:
```

#Virtual Components
virtual:
switch:
  - platform: virtual
    name: TestSwitch 1
    initial_availability: True
  - platform: virtual
    name: Rollo Zustand Auf/Zu
  - platform: virtual
    name: WoZi Tür Auf/Zu
    initial_availability: True
```

and as said worked with core_2023.10.5 without any issue. 

Does somebody have an idea, what could be the issue?

thanks a lot, 
charly
