### ISSUE TITLE
2024.3 warnings in Log: "invalid supported color modes"

### ISSUE THREAD

**Issue by ildar170975** [twrecked/hass-virtual#99]
2024.3

2024-03-07 11:18:00.541 WARNING (MainThread) [homeassistant.components.light] light.virtual_light_1 (<class 'custom_components.virtual.light.VirtualLight'>) sets invalid supported color modes {<ColorMode.BRIGHTNESS: 'brightness'>, <ColorMode.COLOR_TEMP: 'color_temp'>, <ColorMode.HS: 'hs'>, <ColorMode.ONOFF: 'onoff'>}, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/twrecked/hass-virtual/issues

Code:
```
light:
  - platform: virtual
    name: 'Light 1'
    initial_value: 'on'
    support_brightness: true
    initial_brightness: 100
    support_color: true
    initial_color: [0,255]
    support_color_temp: true
    initial_color_temp: 255
    support_white_value: true
    initial_white_value: 240
```
Config set in yaml.
